run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80

  depguard:
    rules:
      main:
        list-mode: strict
        files:
          - "cmd/**"
        allow:
          - $gostd
          - github.com/Azimkhan


linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
#    - deadcode # inactive
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
#    - exportloopref
    - copyloopvar
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
#    - ifshort # inactive
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
#    - structcheck # inactive
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
#    - varcheck # inactive
    - wastedassign
    - whitespace