name: system-stats-integration-test
services:
  integration-test:
    build:
      context: ..
      dockerfile: Dockerfile_test
    image: system-stats-test
    volumes:
      - ..:/code
    environment:
      - CGO_ENABLED=1
    command: "go test -race ./tests/... -v --count=1"