name: system-stats-test
services:
  test:
    build:
      context: ..
      dockerfile: Dockerfile_test
    volumes:
      - ..:/code
    environment:
      - CGO_ENABLED=1
    command: "go test -race ./internal/... -v --count=1"